trigger: none

pool: 
  name: 'RohtasPool'

variables:
  terraformVersion: 1.2.9
  myDirectory: '$(System.DefaultWorkingDirectory)/basic'
  environmentServiceNameAzureRM: 'azure-portal-connection'

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: $(terraformVersion)

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: $(myDirectory)
    backendServiceArm: 'azure-portal-connection'
    backendAzureRmStorageAccountName: 'robinb17storage'
    backendAzureRmContainerName: 'mycontainer'
    backendAzureRmKey: 'myterraform.tfstate'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: $(myDirectory)
    environmentServiceNameAzureRM: $(environmentServiceNameAzureRM)

# Manual validation step, placed in an agentless job
# - job: ManualApprovalJob
#   pool: server  # This makes it an agentless job
#   steps:
#     - task: ManualValidation@1
#       inputs:
#         notifyUsers: 'robinson15kumar@gmail.com'
#         approvers: 'gupta15robinson@gmail.com'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: $(myDirectory)
    commandOptions: '-auto-approve'
    environmentServiceNameAzureRM: $(environmentServiceNameAzureRM)
