
pool: RohtasPool

trigger: none

variables:
  myDirectory: '$(System.DefaultWorkingDirectory)/basic'
steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$myDirectory'
    backendServiceArm: 'azure-portal-connection'
    backendAzureRmStorageAccountName: 'robinb17storage'
    backendAzureRmContainerName: 'mycontainer'
    backendAzureRmKey: 'myterraform.tfstate'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$myDirectory'
    environmentServiceNameAzureRM: 'azure-portal-connection'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$myDirectory'
    commandOptions: '-auto-approve'
    environmentServiceNameAzureRM: 'azure-portal-connection'